name: rocket_trajectory
description: Rocket Fuel & Trajectory Calculator
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.68.0
  math: ^0.0.1  # basic math

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
